create schema net;

create table net.faculty(
    id integer primary key generated by default as identity,
    dean text not null,
    name text not null,
    number_of_students integer not null
);

create table net.department(
    id integer primary key generated by default as identity,
    image bytea,
    manager text not null,
    name text not null,
    number_of_teachers integer not null,
    faculty_id integer not null,
    foreign key(faculty_id) references net.faculty(id)
    on delete cascade
);